// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1m9lUMCLGj6nDrdPTAvPaYnfBXnCMv8',
    appId: '1:285615136885:web:99da2cb224a442570e183c',
    messagingSenderId: '285615136885',
    projectId: 'friendzone-3545a',
    authDomain: 'friendzone-3545a.firebaseapp.com',
    storageBucket: 'friendzone-3545a.appspot.com',
    measurementId: 'G-GW9JKNHYKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2BWbymVtj_8jK0mFQY5jE0iysITj6yM',
    appId: '1:285615136885:android:296faa4a9dc886ad0e183c',
    messagingSenderId: '285615136885',
    projectId: 'friendzone-3545a',
    storageBucket: 'friendzone-3545a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1vAaMbdb4u-nGGr1HyPyABwhUfnWuh1k',
    appId: '1:285615136885:ios:a1ae401d833b6c720e183c',
    messagingSenderId: '285615136885',
    projectId: 'friendzone-3545a',
    storageBucket: 'friendzone-3545a.appspot.com',
    iosClientId: '285615136885-c67lsdt6a8n0gmjrtcptg59ujhfp40ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1vAaMbdb4u-nGGr1HyPyABwhUfnWuh1k',
    appId: '1:285615136885:ios:a1ae401d833b6c720e183c',
    messagingSenderId: '285615136885',
    projectId: 'friendzone-3545a',
    storageBucket: 'friendzone-3545a.appspot.com',
    iosClientId: '285615136885-c67lsdt6a8n0gmjrtcptg59ujhfp40ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzone',
  );
}
