// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqauoeMPgD_XscBHLGk92WH36xfufxr38',
    appId: '1:910759694385:web:2f18c95883dd6972070510',
    messagingSenderId: '910759694385',
    projectId: 'asm-mob403-5ba29',
    authDomain: 'asm-mob403-5ba29.firebaseapp.com',
    databaseURL: 'https://asm-mob403-5ba29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asm-mob403-5ba29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlY4DJJIbxJ-wdCruJwmpRTzU8eYEzSzs',
    appId: '1:910759694385:android:94daceecf5e4b664070510',
    messagingSenderId: '910759694385',
    projectId: 'asm-mob403-5ba29',
    databaseURL: 'https://asm-mob403-5ba29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asm-mob403-5ba29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxjMbJcvyy0cvD0knRQbbyoIW9tZ5bhE',
    appId: '1:910759694385:ios:337feda97928857d070510',
    messagingSenderId: '910759694385',
    projectId: 'asm-mob403-5ba29',
    databaseURL: 'https://asm-mob403-5ba29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asm-mob403-5ba29.appspot.com',
    iosClientId: '910759694385-l0sg5s3m9khhes7je0r2evolvruah10r.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxjMbJcvyy0cvD0knRQbbyoIW9tZ5bhE',
    appId: '1:910759694385:ios:337feda97928857d070510',
    messagingSenderId: '910759694385',
    projectId: 'asm-mob403-5ba29',
    databaseURL: 'https://asm-mob403-5ba29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asm-mob403-5ba29.appspot.com',
    iosClientId: '910759694385-l0sg5s3m9khhes7je0r2evolvruah10r.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzone',
  );
}
